name: Release Nuts
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Release version/name
        required: true

jobs:
  build:
    strategy:
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]  

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri/ -> target/'

      - name: Install npm dependencies
        run: npm ci

      - name: Build the app
        run: npm run tauri build -- --ci

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: |
            ./src-tauri/target/release/NutsClient
            ./src-tauri/target/release/bundle/dmg/*.dmg
            ./src-tauri/target/release/NutsClient.exe

  release:
    permissions:
      contents: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Display structure of downloaded files
        run: ls -R

      - name: Package macOS binary for release
        run: |
          cd ./macos-latest/bundle/dmg/
          tar -czvf Nuts_${{ github.event.inputs.version }}_macOS_Release.tar.gz ./*.dmg

      - name: Package linux binary for release
        run: |
          cd ./ubuntu-latest/
          chmod u+x NutsClient
          tar -czvf Nuts_${{ github.event.inputs.version }}_Linux_Release.tar.gz "NutsClient"
          

      - name: Package Windows binary for release
        run: |
          cd ./windows-latest/
          zip Nuts_${{ github.event.inputs.version }}_Windows_Release.zip "NutsClient.exe"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          generate_release_notes: true
          body: |
            **Important note for macOS users:**

            The macOS release may be affected by an issue with file attributes that can prevent the application from launching correctly. To resolve this, you will need to run the following command in your terminal:

            ```
            xattr -cr ./path/to/your.app
            ```

            **What does this command do?**
            The `xattr` command removes any extended attributes (such as quarantine flags) that macOS adds to files downloaded from the internet. This ensures the app can run without any security warnings or restrictions.

            **Why do you need to run this?**
            macOS sometimes marks downloaded files as coming from an untrusted source, and this can prevent the app from launching properly. Running the `xattr` command clears those flags and allows the app to function normally.
          files: |
            ubuntu-latest/Nuts_${{ github.event.inputs.version }}_Linux_Release.tar.gz
            macos-latest/bundle/dmg/Nuts_${{ github.event.inputs.version }}_macOS_Release.tar.gz
            windows-latest/Nuts_${{ github.event.inputs.version }}_Windows_Release.zip
